### ISSUE TITLE
MYSQL.user 不存在  是什么鬼？

### ISSUE THREAD

**Issue by zthua** [wstart/DB_BaseLine#2]
报了mysql.user 不存在  ，我特地到数据库看了下 ，是存在的  ，
![image](https://user-images.githubusercontent.com/4081273/40477817-f7f7fe44-5f79-11e8-9132-6e7e3d046741.png)

**Comment by wstart** [comment]
你的用户是不是管理员权限啊？

**Comment by hadesfeng** [comment]
我用了root也出现了这种场景，看来还得一个个去看你的代码了
